.PHONY: build test run clean vet race

# NOTE: the C build (see Makefile) also produces bin/spettrum, so the Go build
# uses a distinct name to avoid the two clobbering each other.
BINARY := bin/spettrum-go
CMD := ./cmd/spettrum

build:
	go build -o $(BINARY) $(CMD)

test:
	go test ./...

run: build
	$(BINARY)

vet:
	go vet ./...

race:
	go test -race ./...

clean:
	rm -f $(BINARY)
	go clean -testcache
